# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/open-sdg-site-starter"
url: ""
data_dir: data
environment: staging
# Replace my-github-org and open-sdg-data-starter as needed.
remotedatabaseurl: "https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter"

jekyll_get_json:
  - data: meta
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/meta/all.json'
  - data: headlines
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/headline/all.json'
  - data: schema
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/meta/schema.json'
  - data: reporting
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/stats/reporting.json'
  - data: translations
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.0.json'

analytics:
  ga_prod: ''
 
# Social media accounts.
twitter: 'MyTwitterAccount'

# Replace the email addresses below.
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com

# Github Repo for Data
# Replace this value as needed.
repo_name: open-sdg-data-starter
branch: develop
# Replace this value as needed.
org_name: sustainabledevelopment-kyrgyzstan

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Kyrgyzstan
  adjective: Kyrgyz

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - en

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@0.5.0

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
  
# Mapping
map_options:
  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoiYnJvY2tmYW5uaW5nMSIsImEiOiJjaXplbmgzczgyMmRtMnZxbzlmbGJmdW9pIn0.LU-BYMX69uu3eGgk0Imibg
    attribution: <a href="https://www.mapbox.com">Mapbox</a> | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
  minZoom: 6
map_layers:
  # Country
  - min_zoom: 6
    max_zoom: 8
    serviceUrl: https://github.com/AshKyd/geojson-regions/blob/master/countries/50m/KGZ.geojson
    nameProperty: sovereignt
    idProperty: sov_a3
    staticBorders: true
