# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@0.10.0

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/open-sdg-site-starter"
url: ""
data_dir: data
environment: staging
# Replace "open-sdg" with the name of your GitHub organization, and
# "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "https://open-sdg.github.io/open-sdg-data-starter"
remote_translations:
  - https://open-sdg.github.io/sdg-translations/translations-0.8.1.json

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal
create_pages: true

analytics:
  ga_prod: ''

# Social media accounts.
twitter: 'MyTwitterAccount'

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com

# Github Repo for Data
# Replace this value as needed.
repo_name: open-sdg-data-starter
branch: develop
# Replace this value as needed.
org_name: my-github-org

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Australia
  adjective: Australian

# Optionally uncomment and update the settings below to control the frontpage heading and instructions.
#frontpage_heading: Australian data for Sustainable Development Goal indicators
#frontpage_instructions: Click on each goal, or <span id="jump-to-search"><a>search</a></span>, for Australian statistics for Sustainable Development Goal global indicators.

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - en

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
