# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: ""
url: ""
data_dir: data
environment: production
# Replace my-github-org and open-sdg-data-starter as needed.
remotedatabaseurl: "https://armstat.github.io/sdg-data-armenia/prod"

jekyll_get_json:
  - data: meta
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://armstat.github.io/sdg-data-armenia/prod/meta/all.json'
  - data: headlines
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://armstat.github.io/sdg-data-armenia/prod/headline/all.json'
  - data: schema
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://armstat.github.io/sdg-data-armenia/prod/meta/schema.json'
  - data: translations
    json: 'https://open-sdg.github.io/sdg-translations/translations.json'

analytics:
  ga_prod: 'UA-4464980-1'

# Social media accounts.
#twitter: 'MyTwitterAccount'

# Replace the email addresses below.
email_contacts:
  questions: sdg@armstat.am
  suggestions: sdg@armstat.am
  functional: sdg@armstat.am

# Github Repo for Data
# Replace this value as needed.
repo_name: sdg-data-armenia
branch: develop
# Replace this value as needed.
org_name: armstat

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Armenia
  adjective: Armenian
# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

# The list of languages that are translated. The first one is the default.
languages:
  - en
  - am
  - ru

# Point to remote location for goal images.
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-get-json

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@0.4.0

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
