# ****************************************************************************
# NOTES:
#
# This is an example of a production deployment that uses GitHub Pages along
# with a second "production" GitHub organisation. If you prefer to implement
# your own workflow, or do not need production deployments, then you should
# delete this file.
#
# In order for this to work, you must replace PRODUCTION_ORGANISATION below
# with the name of your production GitHub organisation, under REPOSITORY_NAME.
#
# For example, if your production organisation is "my-stats-org", then use:
#
# REPOSITORY_NAME: my-stats-org/my-stats-org.github.io
#
# ****************************************************************************

name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_prod.yml
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: PRODUCTION_ORGANISATION/PRODUCTION_ORGANISATION.github.io
        ACCESS_TOKEN: ${{ secrets.token }}
        BRANCH: main
        FOLDER: _site
        CLEAN: true
